name: Android CI

on: workflow_dispatch

jobs:
  instrumented_tests:
    name: Instrumented Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
          arguments: build

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace