name: Android CI

# on:
#   pull_request:
#   push:
#     branches:
#       - main

on: workflow_dispatch

jobs:
  instrumented_tests:
    name: Instrumented Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # - name: Setup Emulator
      #   run: emulator 

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest
        uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 30
            target: default
            arch: x86
            profile: Nexus 6
            script: ./gradlew connectedCheck --stacktrace
  
  # lint_project:
  #   name: Lint Project
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.3

  #     - name: Set up JDK environment
  #       uses: actions/setup-java@v1.4.3
  #       with:
  #         java-version: 11

  #     - name: Grant execute permission for gradlew
  #       run: chmod +x gradlew

  #     - name: Build with Gradle
  #       run: ./gradlew build

  #     - name: Run Linter
  #       run: ./gradlew lint
# name: Android CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'temurin'
#         cache: gradle

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build
