name: Hello World!
on:
  pull_request:
  push:
    branches:
      - '*'
jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: helloworld
        run: echo "Hello World"